# Generated by Django 5.2 on 2025-04-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_profile_user'),
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesiredCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pity_counter', models.IntegerField(default=0)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.card')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desired_card', to='accounts.profile')),
            ],
        ),
    ]
