# Generated by Django 5.1.5 on 2025-04-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="currency",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
