# Generated by Django 5.1.5 on 2025-04-12 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_currency"),
        ("pokemon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obtained_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pokemon.card"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_cards",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-obtained_at"],
                "unique_together": {("profile", "card")},
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="cards",
            field=models.ManyToManyField(
                related_name="profiles", through="accounts.UserCard", to="pokemon.card"
            ),
        ),
    ]
