# Generated by Django 5.1.4 on 2025-04-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_cards"),
        ("pokemon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="cards",
        ),
        migrations.AddField(
            model_name="profile",
            name="cards",
            field=models.ManyToManyField(null=True, to="pokemon.card"),
        ),
    ]
