# Generated by Django 5.1.5 on 2025-04-12 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_usercard_profile_cards"),
    ]

    operations = [
        migrations.AlterModelOptions(name="usercard", options={},),
        migrations.AlterUniqueTogether(name="usercard", unique_together=set(),),
        migrations.RemoveField(model_name="profile", name="cards",),
        migrations.AddField(
            model_name="usercard",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collected_cards",
                to="accounts.profile",
            ),
        ),
        migrations.RemoveField(model_name="usercard", name="profile",),
    ]
