# Generated by Django 5.1.5 on 2025-04-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_usercard_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="UserCard",),
    ]
