# Generated by Django 5.1.5 on 2025-04-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_delete_usercard"),
        ("accounts", "0007_alter_profile_user"),
    ]

    operations = []
