# Generated by Django 5.1.4 on 2025-04-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0002_remove_pokemon_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="card_variants",
        ),
    ]
